### PR TITLE
Add example ETH binance config

### PR DESCRIPTION
**Pull request by tastypackets**
Adds an example config for mining direct to Binance pool.

Would have added to the scripts in the downloads too, but it appears those aren't on GitHub. 😄

### CODE REVIEW

**Comment by Unlifate** [comment]
You don't need to set password option (-p). Better to not set it, as it would be a security risk.

**Comment by tastypackets** [comment]
> 
> 
> You don't need to set password option (-p). Better to not set it, as it would be a security risk.

Looks like their examples / setup did remove the password, but their FAQ still says the default password is 12345. I stopped mining to their pool, so can't confirm but I'll update it.

**Comment by Unlifate** [comment]
Awesome. I am still mining to binance pool and can confirm it works without the -p option.

**Comment by wjd000** [comment]
> 
> 
> Awesome. I am still mining to binance pool and can confirm it works without the -p option.

Why I can’t find my miner on binance pool. I run the code "t-rex -a ethash -o stratum+tcp://ethash.poolbinance.com:1800 -u username -w worker1"

**Comment by manuel-rojas** [comment]
> > Awesome. I am still mining to binance pool and can confirm it works without the -p option.
> 
> Why I can’t find my miner on binance pool. I run the code "t-rex -a ethash -o stratum+tcp://ethash.poolbinance.com:1800 -u username -w worker1"

-u "WALLETADDRESS" -w "ACCOUNTNAME"."WORKERNAME"

image

Captura de pantalla 2021-10-09 134336

**Pull request closed without merging**
